## Tensorflow Basic
#### Import package

In [1]:
import tensorflow as tf

#### Define constant in Tensorflow
`tf.constant(value)`

In [2]:
a = tf.constant([1, 2, 3], dtype=tf.int32, name='scalar_a')
b = tf.constant([4, 5, 6])

In [3]:
c = tf.constant([[1, 2, 3], [4, 5, 6]])
d = tf.constant([[1, 2], [3, 4], [5, 6]])

<b>warning</b>: The value isn't shown unless we run it on Tensorflow session

In [4]:
a, b, c, d

(<tf.Tensor 'scalar_a:0' shape=(3,) dtype=int32>,
 <tf.Tensor 'Const:0' shape=(3,) dtype=int32>,
 <tf.Tensor 'Const_1:0' shape=(2, 3) dtype=int32>,
 <tf.Tensor 'Const_2:0' shape=(3, 2) dtype=int32>)

In [5]:
with tf.Session() as session:
    result = session.run(a)
    print(result)

[1 2 3]


#### Basic operation
`tf.add(), tf.subtract(), tf.multiply(), tf.div(), tf.matmul()`

In [6]:
operation = tf.add(a, b)
with tf.Session() as session:
    result = session.run(operation)
    print(result)

[5 7 9]


In [7]:
operation = tf.matmul(c, d)
with tf.Session() as session:
    result = session.run(operation)
    print(result)

[[22 28]
 [49 64]]


`a + b, a - b, a * b, a / b`

In [8]:
operation = a * b
with tf.Session() as session:
    result = session.run(operation)
    print(result)

[ 4 10 18]


#### Define variable in Tensorflow
`tf.Variable(initial_value)`

In [9]:
a = tf.Variable(0)

#### Assign value to variable
`tf.assign(ref_var, new_value)`

In [10]:
update = tf.assign(a, a + 1)

#### Initialize variable
`tf.global_variables_initializer()`<br>
<b>warning</b>: the variables must be initialized before operation

In [11]:
init = tf.global_variables_initializer()
with tf.Session() as session:
    session.run(init)
    print(session.run(a))
    for _ in range(3):
        session.run(update)
        print(session.run(a))

0
1
2
3


#### Placeholder
`tf.placeholder(datatype)`<br>
Placeholder can be used to feed data from outside the Tensorflow graph. Also check: [data types](https://www.tensorflow.org/api_docs/python/tf/dtypes/DType) 

In [12]:
x = tf.placeholder(tf.float16)
y = 2 * x + 3

with tf.Session() as session:
    result = session.run(y, feed_dict={x: [[1, 2, 3], [4, 5, 6]]})
    print(result)

[[  5.   7.   9.]
 [ 11.  13.  15.]]
